rvm:
  - 2.2.0

services:
  - mongodb

install:
  - ./linux-setup.sh
  - sudo ./setup.sh
  - sudo npm install mocha-phantomjs phantomjs

before_script:
  - sudo rm /var/lib/mongodb/mongod.lock
  - sudo service mongodb restart
  - sleep 15

script:
  - ./js_test.sh
  - source ~/.virtualenv/rmc/bin/activate
  - make test
